const mongoose = require('mongoose');
const dotenv = require('dotenv');

// Load env vars
dotenv.config();

// Import models
const Trainer = require('./models/Trainer');
const Subscription = require('./models/Subscription');
const Class = require('./models/Class');
const User = require('./models/User');

// Connect to DB
mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/fitzone');

// Admin User Data
const adminUserData = {
  fullName: 'Admin User',
  email: 'admin@fitzone.com',
  password: 'admin123', // Will be hashed
  phone: '+1 (555) 000-0001',
  role: 'admin',
};

// Sample Trainers Data
const trainersData = [
  {
    name: 'Marcus Johnson',
    email: 'marcus@fitzone.com',
    phone: '+1 (555) 123-4567',
    image: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=400&h=400&fit=crop',
    specializations: ['Strength Training', 'HIIT', 'Muscle Building'],
    experience: 8,
    bio: 'Former professional athlete turned fitness coach. Marcus specializes in strength training and high-intensity workouts that deliver real results. His motivational approach has helped hundreds of clients achieve their fitness goals.',
    hourlyRate: 75,
    rating: 4.9,
    totalReviews: 156,
    totalClients: 200,
    certifications: [
      { name: 'NASM Certified Personal Trainer', issuer: 'NASM', year: 2016 },
      { name: 'CrossFit Level 2', issuer: 'CrossFit Inc.', year: 2018 },
    ],
    achievements: ['200+ Clients Trained', 'Former Pro Athlete', 'Nutrition Specialist'],
    socialMedia: { instagram: '@marcus_fit', twitter: '@marcusjohnson' },
    availability: [
      { day: 'Monday', startTime: '06:00', endTime: '14:00' },
      { day: 'Wednesday', startTime: '06:00', endTime: '14:00' },
      { day: 'Friday', startTime: '06:00', endTime: '14:00' },
    ],
    isAvailable: true,
  },
  {
    name: 'Sarah Chen',
    email: 'sarah@fitzone.com',
    phone: '+1 (555) 234-5678',
    image: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400&h=400&fit=crop',
    specializations: ['Yoga', 'Pilates', 'Meditation'],
    experience: 10,
    bio: 'Certified yoga instructor with over a decade of experience. Sarah combines traditional yoga practices with modern wellness techniques to help you find balance, flexibility, and inner peace.',
    hourlyRate: 65,
    rating: 4.8,
    totalReviews: 203,
    totalClients: 350,
    certifications: [
      { name: 'RYT-500 Yoga Alliance', issuer: 'Yoga Alliance', year: 2014 },
      { name: 'Pilates Method Alliance', issuer: 'PMA', year: 2016 },
    ],
    achievements: ['500+ Hours Yoga Training', '10 Years Experience', 'Mindfulness Expert'],
    socialMedia: { instagram: '@sarahyoga', facebook: 'sarahchenyoga' },
    availability: [
      { day: 'Tuesday', startTime: '07:00', endTime: '15:00' },
      { day: 'Thursday', startTime: '07:00', endTime: '15:00' },
      { day: 'Saturday', startTime: '08:00', endTime: '12:00' },
    ],
    isAvailable: true,
  },
  {
    name: 'David Rodriguez',
    email: 'david@fitzone.com',
    phone: '+1 (555) 345-6789',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop',
    specializations: ['Boxing', 'Kickboxing', 'Cardio'],
    experience: 12,
    bio: 'Professional boxing coach with competitive fighting background. David brings intensity and discipline to every session, helping clients build endurance, strength, and confidence through combat sports training.',
    hourlyRate: 80,
    rating: 4.9,
    totalReviews: 178,
    totalClients: 180,
    certifications: [
      { name: 'USA Boxing Coach', issuer: 'USA Boxing', year: 2012 },
      { name: 'ACE Certified Personal Trainer', issuer: 'ACE', year: 2014 },
    ],
    achievements: ['Former Pro Boxer', 'National Champion Coach', '12 Years Experience'],
    socialMedia: { instagram: '@davidboxing', twitter: '@davidrodriguez' },
    availability: [
      { day: 'Monday', startTime: '14:00', endTime: '21:00' },
      { day: 'Wednesday', startTime: '14:00', endTime: '21:00' },
      { day: 'Friday', startTime: '14:00', endTime: '21:00' },
    ],
    isAvailable: true,
  },
  {
    name: 'Emily Thompson',
    email: 'emily@fitzone.com',
    phone: '+1 (555) 456-7890',
    image: 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=400&h=400&fit=crop',
    specializations: ['CrossFit', 'Functional Training', 'HIIT'],
    experience: 6,
    bio: 'CrossFit Games competitor and certified coach. Emily designs challenging workouts that push your limits while ensuring proper form and technique. Her high-energy sessions will transform your fitness level.',
    hourlyRate: 70,
    rating: 4.7,
    totalReviews: 134,
    totalClients: 150,
    certifications: [
      { name: 'CrossFit Level 3', issuer: 'CrossFit Inc.', year: 2019 },
      { name: 'USAW Sports Performance Coach', issuer: 'USA Weightlifting', year: 2020 },
    ],
    achievements: ['CrossFit Games Competitor', 'Olympic Lifting Specialist', '150+ Members Coached'],
    socialMedia: { instagram: '@emilycrossfit', facebook: 'emilythompsonfitness' },
    availability: [
      { day: 'Tuesday', startTime: '05:00', endTime: '13:00' },
      { day: 'Thursday', startTime: '05:00', endTime: '13:00' },
      { day: 'Saturday', startTime: '07:00', endTime: '14:00' },
    ],
    isAvailable: true,
  },
  {
    name: 'Michael Park',
    email: 'michael@fitzone.com',
    phone: '+1 (555) 567-8901',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=400&fit=crop',
    specializations: ['Swimming', 'Cardio', 'Weight Loss'],
    experience: 9,
    bio: 'Former Olympic swimming coach now dedicated to personal fitness training. Michael specializes in aquatic fitness and cardio programs that are easy on joints but incredibly effective for weight loss and endurance.',
    hourlyRate: 70,
    rating: 4.8,
    totalReviews: 145,
    totalClients: 220,
    certifications: [
      { name: 'USA Swimming Coach', issuer: 'USA Swimming', year: 2015 },
      { name: 'AFAA Group Fitness', issuer: 'AFAA', year: 2017 },
    ],
    achievements: ['Olympic Team Coach', 'Aquatic Fitness Expert', '9 Years Experience'],
    socialMedia: { instagram: '@michaelswim', twitter: '@mparkfitness' },
    availability: [
      { day: 'Monday', startTime: '08:00', endTime: '16:00' },
      { day: 'Wednesday', startTime: '08:00', endTime: '16:00' },
      { day: 'Friday', startTime: '08:00', endTime: '16:00' },
    ],
    isAvailable: true,
  },
  {
    name: 'Jessica Williams',
    email: 'jessica@fitzone.com',
    phone: '+1 (555) 678-9012',
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=400&fit=crop',
    specializations: ['Zumba', 'Dance Fitness', 'Cardio'],
    experience: 7,
    bio: 'Licensed Zumba instructor who makes fitness fun! Jessica\'s high-energy dance classes combine Latin rhythms with effective cardio workouts. Perfect for anyone who wants to get fit while having a blast.',
    hourlyRate: 55,
    rating: 4.9,
    totalReviews: 267,
    totalClients: 400,
    certifications: [
      { name: 'Zumba Fitness Instructor', issuer: 'Zumba', year: 2017 },
      { name: 'AFAA Group Exercise', issuer: 'AFAA', year: 2018 },
    ],
    achievements: ['400+ Students', 'Zumba Jammer', 'Dance Fitness Expert'],
    socialMedia: { instagram: '@jessicazumba', facebook: 'jessicawilliamszumba' },
    availability: [
      { day: 'Tuesday', startTime: '16:00', endTime: '21:00' },
      { day: 'Thursday', startTime: '16:00', endTime: '21:00' },
      { day: 'Sunday', startTime: '09:00', endTime: '14:00' },
    ],
    isAvailable: true,
  },
  {
    name: 'Alex Martinez',
    email: 'alex@fitzone.com',
    phone: '+1 (555) 789-0123',
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=400&fit=crop',
    specializations: ['Spinning', 'Cardio', 'HIIT'],
    experience: 5,
    bio: 'Certified spinning instructor with infectious energy. Alex\'s cycling classes are legendary - combining powerful playlists with interval training that will push you to new limits while having an amazing time.',
    hourlyRate: 60,
    rating: 4.7,
    totalReviews: 189,
    totalClients: 280,
    certifications: [
      { name: 'Spinning Certified Instructor', issuer: 'Spinning', year: 2019 },
      { name: 'ACE Group Fitness', issuer: 'ACE', year: 2020 },
    ],
    achievements: ['Master Instructor', 'Music Curator', '5 Years Experience'],
    socialMedia: { instagram: '@alexspins', twitter: '@alexmartinezfit' },
    availability: [
      { day: 'Monday', startTime: '05:00', endTime: '09:00' },
      { day: 'Wednesday', startTime: '05:00', endTime: '09:00' },
      { day: 'Friday', startTime: '17:00', endTime: '21:00' },
    ],
    isAvailable: true,
  },
  {
    name: 'Dr. Rachel Foster',
    email: 'rachel@fitzone.com',
    phone: '+1 (555) 890-1234',
    image: 'https://images.unsplash.com/photo-1571019613576-2b22c76fd955?w=400&h=400&fit=crop',
    specializations: ['Nutrition', 'Weight Loss', 'Personal Training'],
    experience: 11,
    bio: 'PhD in Sports Nutrition and certified personal trainer. Dr. Rachel combines exercise science with nutritional expertise to create comprehensive transformation programs. Her evidence-based approach guarantees results.',
    hourlyRate: 90,
    rating: 4.9,
    totalReviews: 312,
    totalClients: 500,
    certifications: [
      { name: 'PhD Sports Nutrition', issuer: 'Stanford University', year: 2013 },
      { name: 'NSCA-CSCS', issuer: 'NSCA', year: 2014 },
    ],
    achievements: ['PhD Nutrition', '500+ Transformations', 'Published Author'],
    socialMedia: { instagram: '@drrachelfoster', facebook: 'drrachelnutrition' },
    availability: [
      { day: 'Tuesday', startTime: '09:00', endTime: '17:00' },
      { day: 'Thursday', startTime: '09:00', endTime: '17:00' },
      { day: 'Saturday', startTime: '10:00', endTime: '15:00' },
    ],
    isAvailable: true,
  },
];

// Sample Subscription Plans Data
const subscriptionsData = [
  {
    name: 'Basic',
    slug: 'basic',
    price: 29,
    originalPrice: 39,
    duration: 1,
    description: 'Perfect for beginners starting their fitness journey',
    features: [
      'Access to gym facilities',
      'Basic equipment usage',
      '2 group classes per week',
      'Locker room access',
      'Free WiFi',
      'Fitness assessment',
    ],
    highlights: ['No commitment', 'Cancel anytime'],
    maxClassesPerMonth: 8,
    personalTrainerAccess: false,
    personalTrainingSessions: 0,
    nutritionPlanIncluded: false,
    lockerAccess: true,
    guestPasses: 0,
    freezeOption: false,
    priority: 1,
    isPopular: false,
    color: 'primary',
    isActive: true,
  },
  {
    name: 'Pro',
    slug: 'pro',
    price: 59,
    originalPrice: 79,
    duration: 1,
    description: 'Most popular choice for dedicated fitness enthusiasts',
    features: [
      'Full gym access 24/7',
      'All equipment & amenities',
      'Unlimited group classes',
      'Sauna & steam room',
      '1 personal training session/month',
      'Nutrition consultation',
      'Towel service',
      'Priority booking',
      'FitZone app premium',
    ],
    highlights: ['Best value', '24/7 access', 'Most popular'],
    maxClassesPerMonth: 0, // Unlimited
    personalTrainerAccess: true,
    personalTrainingSessions: 1,
    nutritionPlanIncluded: true,
    lockerAccess: true,
    guestPasses: 2,
    freezeOption: true,
    priority: 2,
    isPopular: true,
    color: 'secondary',
    isActive: true,
  },
  {
    name: 'Elite',
    slug: 'elite',
    price: 99,
    originalPrice: 149,
    duration: 1,
    description: 'Premium experience with exclusive perks and personalized attention',
    features: [
      'Everything in Pro plan',
      'Unlimited personal training',
      'Custom meal plans',
      'Recovery room access',
      'Private locker',
      'Complimentary supplements',
      'Priority class booking',
      '5 guest passes/month',
      'Exclusive member events',
      'Free parking',
      'Spa discounts',
      '24/7 trainer support',
    ],
    highlights: ['All inclusive', 'VIP treatment', 'Unlimited training'],
    maxClassesPerMonth: 0, // Unlimited
    personalTrainerAccess: true,
    personalTrainingSessions: 0, // Unlimited
    nutritionPlanIncluded: true,
    lockerAccess: true,
    guestPasses: 5,
    freezeOption: true,
    priority: 3,
    isPopular: false,
    color: 'accent',
    isActive: true,
  },
];

// Sample Programs/Classes Data
const classesData = [
  {
    name: 'Power Yoga',
    slug: 'power-yoga',
    description: 'A vigorous, fitness-based approach to vinyasa-style yoga. Build strength, flexibility, and balance while connecting breath with movement. This class is perfect for those looking to combine the mindfulness of yoga with a challenging physical workout.',
    shortDescription: 'Vigorous vinyasa-style yoga combining strength, flexibility, and mindfulness.',
    type: 'Yoga',
    category: 'Mind & Body',
    trainerName: 'Sarah Chen',
    duration: 60,
    capacity: 25,
    difficulty: 'intermediate',
    location: 'Studio A',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    icon: '🧘',
    color: 'purple',
    benefits: ['Increased flexibility', 'Core strength', 'Stress relief', 'Better posture', 'Mental clarity'],
    equipment: ['Yoga mat', 'Blocks', 'Strap'],
    calories: 350,
    intensity: 'Medium',
    rating: 4.8,
    totalReviews: 234,
    schedules: [
      { day: 'Monday', startTime: '07:00', endTime: '08:00' },
      { day: 'Wednesday', startTime: '07:00', endTime: '08:00' },
      { day: 'Friday', startTime: '18:00', endTime: '19:00' },
    ],
    isPopular: true,
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'HIIT Blast',
    slug: 'hiit-blast',
    description: 'High-Intensity Interval Training that will push your limits! Alternating between intense bursts of activity and fixed periods of less-intense activity or rest. Get maximum results in minimum time with this calorie-torching workout.',
    shortDescription: 'Maximum results in minimum time with high-intensity interval training.',
    type: 'HIIT',
    category: 'Cardio',
    trainerName: 'Marcus Johnson',
    duration: 45,
    capacity: 20,
    difficulty: 'advanced',
    location: 'Main Floor',
    image: 'https://images.unsplash.com/photo-1534258936925-c58bed479fcb?w=800',
    icon: '🔥',
    color: 'red',
    benefits: ['Fat burning', 'Improved endurance', 'Metabolic boost', 'Cardiovascular health', 'Time efficient'],
    equipment: ['Dumbbells', 'Kettlebells', 'Jump rope', 'Battle ropes'],
    calories: 600,
    intensity: 'Very High',
    rating: 4.9,
    totalReviews: 312,
    schedules: [
      { day: 'Tuesday', startTime: '06:00', endTime: '06:45' },
      { day: 'Thursday', startTime: '06:00', endTime: '06:45' },
      { day: 'Saturday', startTime: '09:00', endTime: '09:45' },
    ],
    isPopular: true,
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Strength & Conditioning',
    slug: 'strength-conditioning',
    description: 'Build lean muscle mass and functional strength with this comprehensive strength training program. Learn proper form and technique while progressively challenging your muscles for maximum growth and definition.',
    shortDescription: 'Build lean muscle and functional strength with progressive training.',
    type: 'Strength Training',
    category: 'Strength',
    trainerName: 'Marcus Johnson',
    duration: 60,
    capacity: 15,
    difficulty: 'intermediate',
    location: 'Weight Room',
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c149a?w=800',
    icon: '💪',
    color: 'blue',
    benefits: ['Muscle building', 'Increased metabolism', 'Bone density', 'Functional strength', 'Better posture'],
    equipment: ['Barbells', 'Dumbbells', 'Cable machines', 'Benches'],
    calories: 450,
    intensity: 'High',
    rating: 4.7,
    totalReviews: 189,
    schedules: [
      { day: 'Monday', startTime: '17:00', endTime: '18:00' },
      { day: 'Wednesday', startTime: '17:00', endTime: '18:00' },
      { day: 'Friday', startTime: '17:00', endTime: '18:00' },
    ],
    isPopular: true,
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Boxing Fundamentals',
    slug: 'boxing-fundamentals',
    description: 'Learn the sweet science of boxing! This class covers proper stance, footwork, punches, and combinations. Get an incredible full-body workout while learning real boxing techniques from a professional coach.',
    shortDescription: 'Learn real boxing techniques for an incredible full-body workout.',
    type: 'Boxing',
    category: 'Combat',
    trainerName: 'David Rodriguez',
    duration: 60,
    capacity: 16,
    difficulty: 'all-levels',
    location: 'Boxing Studio',
    image: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800',
    icon: '🥊',
    color: 'orange',
    benefits: ['Self-defense skills', 'Stress relief', 'Coordination', 'Full-body workout', 'Confidence'],
    equipment: ['Boxing gloves', 'Hand wraps', 'Heavy bags', 'Speed bags'],
    calories: 500,
    intensity: 'High',
    rating: 4.9,
    totalReviews: 267,
    schedules: [
      { day: 'Monday', startTime: '19:00', endTime: '20:00' },
      { day: 'Wednesday', startTime: '19:00', endTime: '20:00' },
      { day: 'Saturday', startTime: '11:00', endTime: '12:00' },
    ],
    isPopular: true,
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Zumba Party',
    slug: 'zumba-party',
    description: 'Dance your way to fitness! This Latin-inspired dance fitness class combines high-energy music with easy-to-follow moves. No dance experience needed - just bring your energy and get ready to have fun!',
    shortDescription: 'Latin-inspired dance fitness with high-energy music and fun moves.',
    type: 'Zumba',
    category: 'Dance',
    trainerName: 'Jessica Williams',
    duration: 55,
    capacity: 30,
    difficulty: 'beginner',
    location: 'Studio B',
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800',
    icon: '💃',
    color: 'pink',
    benefits: ['Cardio fitness', 'Coordination', 'Mood boost', 'Calorie burning', 'Social fun'],
    equipment: ['None required'],
    calories: 400,
    intensity: 'Medium',
    rating: 4.8,
    totalReviews: 345,
    schedules: [
      { day: 'Tuesday', startTime: '18:00', endTime: '18:55' },
      { day: 'Thursday', startTime: '18:00', endTime: '18:55' },
      { day: 'Sunday', startTime: '10:00', endTime: '10:55' },
    ],
    isPopular: true,
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'CrossFit WOD',
    slug: 'crossfit-wod',
    description: 'Experience the CrossFit methodology with constantly varied functional movements performed at high intensity. Each day brings a new Workout of the Day (WOD) designed to challenge and improve your overall fitness.',
    shortDescription: 'Daily varied functional movements at high intensity.',
    type: 'CrossFit',
    category: 'Strength',
    trainerName: 'Emily Thompson',
    duration: 60,
    capacity: 15,
    difficulty: 'advanced',
    location: 'CrossFit Box',
    image: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800',
    icon: '🏋️',
    color: 'green',
    benefits: ['Full-body fitness', 'Community support', 'Strength gains', 'Athletic performance', 'Mental toughness'],
    equipment: ['Barbells', 'Pull-up bars', 'Rowing machines', 'Boxes'],
    calories: 650,
    intensity: 'Very High',
    rating: 4.7,
    totalReviews: 198,
    schedules: [
      { day: 'Monday', startTime: '05:30', endTime: '06:30' },
      { day: 'Wednesday', startTime: '05:30', endTime: '06:30' },
      { day: 'Friday', startTime: '05:30', endTime: '06:30' },
    ],
    isPopular: false,
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Spin Class',
    slug: 'spin-class',
    description: 'Indoor cycling at its finest! Ride to the beat of motivating music through flat roads, hills, and sprints. This low-impact, high-intensity workout is perfect for all fitness levels looking to improve cardiovascular health.',
    shortDescription: 'High-energy indoor cycling with motivating music and interval training.',
    type: 'Spinning',
    category: 'Cardio',
    trainerName: 'Alex Martinez',
    duration: 45,
    capacity: 25,
    difficulty: 'all-levels',
    location: 'Cycling Studio',
    image: 'https://images.unsplash.com/photo-1534787238916-9ba6764efd4f?w=800',
    icon: '🚴',
    color: 'cyan',
    benefits: ['Low impact cardio', 'Leg strength', 'Endurance', 'Calorie burning', 'Mental focus'],
    equipment: ['Spin bikes', 'Heart rate monitors'],
    calories: 500,
    intensity: 'High',
    rating: 4.8,
    totalReviews: 278,
    schedules: [
      { day: 'Monday', startTime: '06:00', endTime: '06:45' },
      { day: 'Wednesday', startTime: '06:00', endTime: '06:45' },
      { day: 'Friday', startTime: '18:00', endTime: '18:45' },
    ],
    isPopular: true,
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Pilates Core',
    slug: 'pilates-core',
    description: 'Focus on core strength, flexibility, and body awareness with controlled movements. This mat-based Pilates class emphasizes proper alignment and breathing while building a strong foundation from your center.',
    shortDescription: 'Core-focused mat Pilates for strength, flexibility, and body awareness.',
    type: 'Pilates',
    category: 'Flexibility',
    trainerName: 'Sarah Chen',
    duration: 50,
    capacity: 20,
    difficulty: 'beginner',
    location: 'Studio A',
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800',
    icon: '🎯',
    color: 'teal',
    benefits: ['Core strength', 'Flexibility', 'Posture improvement', 'Back pain relief', 'Mind-body connection'],
    equipment: ['Pilates mat', 'Resistance bands', 'Magic circle'],
    calories: 250,
    intensity: 'Low',
    rating: 4.9,
    totalReviews: 156,
    schedules: [
      { day: 'Tuesday', startTime: '09:00', endTime: '09:50' },
      { day: 'Thursday', startTime: '09:00', endTime: '09:50' },
      { day: 'Saturday', startTime: '10:00', endTime: '10:50' },
    ],
    isPopular: false,
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Aqua Fitness',
    slug: 'aqua-fitness',
    description: 'Low-impact, high-resistance workout in the pool! Perfect for all fitness levels and especially beneficial for those with joint issues. The water provides natural resistance while being gentle on your body.',
    shortDescription: 'Low-impact pool workout with high resistance, gentle on joints.',
    type: 'Swimming',
    category: 'Aquatic',
    trainerName: 'Michael Park',
    duration: 45,
    capacity: 20,
    difficulty: 'beginner',
    location: 'Indoor Pool',
    image: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800',
    icon: '🏊',
    color: 'blue',
    benefits: ['Joint-friendly', 'Full-body workout', 'Improved mobility', 'Cardiovascular health', 'Muscle toning'],
    equipment: ['Pool noodles', 'Water weights', 'Kickboards'],
    calories: 350,
    intensity: 'Low',
    rating: 4.7,
    totalReviews: 134,
    schedules: [
      { day: 'Monday', startTime: '10:00', endTime: '10:45' },
      { day: 'Wednesday', startTime: '10:00', endTime: '10:45' },
      { day: 'Friday', startTime: '10:00', endTime: '10:45' },
    ],
    isPopular: false,
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Kickboxing Cardio',
    slug: 'kickboxing-cardio',
    description: 'High-energy cardio kickboxing that combines martial arts techniques with fast-paced cardio. Punch, kick, and knee your way to better fitness while learning real kickboxing moves in a fun, non-contact environment.',
    shortDescription: 'High-energy cardio with martial arts techniques in a fun, non-contact class.',
    type: 'Kickboxing',
    category: 'Combat',
    trainerName: 'David Rodriguez',
    duration: 55,
    capacity: 20,
    difficulty: 'intermediate',
    location: 'Boxing Studio',
    image: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800',
    icon: '🦵',
    color: 'red',
    benefits: ['Cardio fitness', 'Stress relief', 'Self-defense awareness', 'Coordination', 'Core strength'],
    equipment: ['Boxing gloves', 'Kick pads'],
    calories: 550,
    intensity: 'High',
    rating: 4.8,
    totalReviews: 203,
    schedules: [
      { day: 'Tuesday', startTime: '19:00', endTime: '19:55' },
      { day: 'Thursday', startTime: '19:00', endTime: '19:55' },
      { day: 'Saturday', startTime: '14:00', endTime: '14:55' },
    ],
    isPopular: true,
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Functional Training',
    slug: 'functional-training',
    description: 'Train your body for real-life movements! This class focuses on exercises that mimic everyday activities, improving your strength, balance, and coordination for better daily performance.',
    shortDescription: 'Real-life movement training for strength, balance, and coordination.',
    type: 'Functional Training',
    category: 'Strength',
    trainerName: 'Emily Thompson',
    duration: 50,
    capacity: 15,
    difficulty: 'all-levels',
    location: 'Functional Zone',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800',
    icon: '⚡',
    color: 'yellow',
    benefits: ['Practical strength', 'Injury prevention', 'Balance improvement', 'Core stability', 'Daily life performance'],
    equipment: ['TRX', 'Medicine balls', 'Kettlebells', 'Resistance bands'],
    calories: 400,
    intensity: 'Medium',
    rating: 4.6,
    totalReviews: 167,
    schedules: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50' },
      { day: 'Friday', startTime: '12:00', endTime: '12:50' },
    ],
    isPopular: false,
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Meditation & Breathwork',
    slug: 'meditation-breathwork',
    description: 'Find your inner calm with guided meditation and breathing exercises. Learn techniques to reduce stress, improve focus, and enhance overall well-being. Perfect for beginners and experienced practitioners alike.',
    shortDescription: 'Guided meditation and breathing techniques for stress relief and focus.',
    type: 'Meditation',
    category: 'Mind & Body',
    trainerName: 'Sarah Chen',
    duration: 30,
    capacity: 30,
    difficulty: 'beginner',
    location: 'Zen Room',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    icon: '🧠',
    color: 'indigo',
    benefits: ['Stress reduction', 'Mental clarity', 'Better sleep', 'Emotional balance', 'Mindfulness'],
    equipment: ['Meditation cushion', 'Blanket'],
    calories: 50,
    intensity: 'Low',
    rating: 4.9,
    totalReviews: 189,
    schedules: [
      { day: 'Tuesday', startTime: '07:00', endTime: '07:30' },
      { day: 'Thursday', startTime: '07:00', endTime: '07:30' },
      { day: 'Sunday', startTime: '08:00', endTime: '08:30' },
    ],
    isPopular: false,
    isFeatured: true,
    isActive: true,
  },
];

// Seed function
const seedDatabase = async () => {
  try {
    // Clear existing data
    await Trainer.deleteMany({});
    await Subscription.deleteMany({});
    await Class.deleteMany({});
    await User.deleteMany({ role: 'admin' }); // Only delete admin users

    console.log('🗑️  Cleared existing data');

    // Create admin user (password will be hashed by pre-save hook)
    const adminUser = await User.create(adminUserData);
    console.log(`✅ Created admin user: ${adminUser.email}`);

    // Insert trainers
    const trainers = await Trainer.insertMany(trainersData);
    console.log(`✅ Inserted ${trainers.length} trainers`);

    // Insert subscriptions
    const subscriptions = await Subscription.insertMany(subscriptionsData);
    console.log(`✅ Inserted ${subscriptions.length} subscription plans`);

    // Insert classes/programs
    const classes = await Class.insertMany(classesData);
    console.log(`✅ Inserted ${classes.length} programs/classes`);

    console.log('\n🎉 Database seeded successfully!');
    console.log('-----------------------------------');
    console.log(`Admin User: admin@fitzone.com / admin123`);
    console.log(`Trainers: ${trainers.length}`);
    console.log(`Plans: ${subscriptions.length}`);
    console.log(`Programs: ${classes.length}`);
    
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

// Run seeder
seedDatabase();
