module.exports = {
  User: require('./User'),
  Member: require('./Member'),
  Trainer: require('./Trainer'),
  Class: require('./Class'),
  Subscription: require('./Subscription'),
  Equipment: require('./Equipment'),
  Attendance: require('./Attendance'),
  QRToken: require('./QRToken'),
  Message: require('./Message'),
  Conversation: require('./Conversation'),
  Product: require('./Product'),
  Cart: require('./Cart'),
  Order: require('./Order'),
};
